version: '2'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - "./public:/usr/share/nginx/html"
    environment:
      APP_PORT: 9000

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql"
